### ISSUE TITLE
using RenderImage and trying to apply the style attribute

### ISSUE THREAD

**Issue by acesaver** [mikeedwards83/Glass.Mapper#120]
Looked into this issue myself and found that in GlassHtml.cs in the foreach loop that deals with the attributes passed into the method, the switch statement does not handle the "style" attribute so it falls through to the default case which adds the style attribute to the url and html producing a url that looks like this.

/~/media/pma-images/pillars/pillar_icons_circle_globalconnections_es.png?h=48&amp;w=48&amp;style=max-width: 48px; height: auto; display: block; margin: 0 auto;

which is invalid for html email formats (questionable valid format for browsers? seems to work fine, but still not correct). The "style" attribute should only be added to the html.

Usage example that created this url

var imageParameters = new ImageParameters { Width = 48, Height = 48 };
	imageParameters.Parameters.Add("style", "max-width: 48px; height: auto; display: block; margin: 0 auto;");

@RenderAbsoluteImage(x => x.Pillar_Icon, imageParameters, true)

included is a screenshot of the process in question located in GlassHtml.cs method with signature

public virtual string RenderImage(Fields.Image image, NameValueCollection attributes)

![image](https://cloud.githubusercontent.com/assets/873675/7028411/b726a496-dd23-11e4-8aad-d30a3b519c3a.png)

we are using glass.mapper version 3.0.10.23 and Glass.Mapper.Sc version 3.1.8.28

**Comment by mikeedwards83** [comment]
I have pushed a fix to our develop branch. This is available from the nightly build as 4.0.1.27

**Comment by mikeedwards83** [comment]
This has been release in 4.0.1.8, reopen if this is still and issue.

**Comment by SanderSchutten** [comment]
Although i understand why the fix is done. It's posing a problem in my solution.
We have developed our own  ImageProcessor which does some special effects like blurring of the image. We had this working with adding a parameter to the querystring, like: /~/image.jpg&w=100&h=100&process=blur. After the recent fix, we see that the "process"-attribute is no longer being added to the querystring. Is it maybe an idea to force parameters onto the querystring if they start with a underscore? Or add another RenderImage-overload with a querystring-parameters-dictionairy?
The fix has broken our custom solution...

**Comment by mikeedwards83** [comment]
fixed in 4.0.2
