### ISSUE TITLE
GlassController GetContextFromHttp() is throwing an error

### ISSUE THREAD

**Issue by sergio-bazan** [mikeedwards83/Glass.Mapper#185]
Hi,

I'm having an error when I'm trying to instantiate the Controller for unit test.
This error was not happening in the previous version (v3), it seems that it was an update in the static method GetContextFromHttp. I was checking the code in this link  https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc.Mvc/Web/Mvc/GlassController.cs and found that is related to the Sitecore.Diagnostic.Log.Error method in the catch.

It's trying to log the error but is calling the method with null in the ownerType:
Log.Error("Failed to create SitecoreContext", ex, null);

Has someone had the same error? or someone found a solution to this issue?
Thanks!

StackTrace:
at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
at Sitecore.Diagnostics.Log.Error(String message, Exception exception, Type ownerType)
at Glass.Mapper.Sc.Web.Mvc.GlassController.GetContextFromHttp()
at Glass.Mapper.Sc.Web.Mvc.GlassController..ctor()

Regards,
Sergio Bazán

**Comment by halovanic** [comment]
I also saw the same issue on an upgrade for my unit tests.  It seems the line should be:
`Log.Error("Failed to create SitecoreContext", ex, typeof(GlassController));`
The GetContextFromHttp method will then return a null instead of an exception, as the intention seems to be.

After getting past that, I found a couple of other issues that blocked my existing unit tests:
1. GlassHtml cannot be instantiated with a null SitecoreContext in the protected constructor (it is null from the above method).  Assuming we're not patching GlassHtml, then this would require another null check: `sitecoreContext == null ? null : new GlassHtml(sitecoreContext)`
2. RenderingContextWrapper is protected instead of public like GlassHtml and SitecoreContext.  This makes it impossible to override the injected implementation for unit tests, assuming you're trying to cover the no-argument constructor.

Thanks,
Alex Halovanic

**Comment by cardinal252** [comment]
I recently wrote a long blog post on unit testing the GlassController class, indeed there are unit tests for it in the Glass Mapper codebase.

There are plenty of examples of unit tests for GlassController here:

https://github.com/mikeedwards83/Glass.Mapper/tree/develop/Tests/Unit%20Tests/Glass.Mapper.Sc.Mvc.Tests

and a long post about it here:

http://cardinalcore.co.uk/2015/09/29/life-through-a-lens-unit-testing-with-glass-controllers/

Though the blog post was written on a pre-release, so the gists are subtley out of date.

**Comment by mikeedwards83** [comment]
This line has been updated as per the comment by @halovanic:

Log.Error("Failed to create SitecoreContext", ex, typeof(GlassController));

I have also added a null check to the construction of GlassHtml

Commit: https://github.com/mikeedwards83/Glass.Mapper/commit/5f9d659d225008bfa9288ab7963dee6be2dfaa1c

**Comment by sergio-bazan** [comment]
Thanks guys for the quick response, all the response were helpful.
@mikeedwards83 Do you know when is going to be this update available in Nuget?
(Sorry for the silly question, I'm not sure how this process works)

Regards,
Sergio Bazán

**Comment by mikeedwards83** [comment]
Once it is marked as ready it goes into the develop branch. This is build overnight on the Glass build server as a beta. About once a month we then do a release to the master branch and push this live. This should be soon.

**Comment by sergio-bazan** [comment]
Thanks @mikeedwards83 !

**Comment by mikeedwards83** [comment]
Released in 4.0.4
