### ISSUE TITLE
In Page Editor rendering an ImageField will write width / height attributes in img tag

### ISSUE THREAD

**Issue by z00mable** [mikeedwards83/Glass.Mapper#201]
When one of the following is used, width / height attributes are written in the img tag, although it is not wanted:

    @Html.Glass().RenderImage(Model, x=> x.ImageField, outputHeightWidth:false, isEditable:true, parameters:new {mw = 1218, mh = 530})

    @Html.Glass().Editable(x => x.ImageField, new { mw = 1218, mh = 530, width = (string)null, height = (string)null })

We always get

    <img src="http://url_to_local_website/-/media/image_1218x530.jpg?h=530&amp;la=en&amp;mh=530&amp;mw=1218&amp;w=1216&amp;hash=452505F9D5896956CB6B0F284755555217E62D8A" alt="Alt Text" width="1216" height="530" sc-part-of="field" class="scEnabledChrome">

So even when using the explicit parameter `outputHeightWidth:false` it outputs width and height attributes in Page Editor and distorts the image. Any suggestions? Or is it a bug?

In a comment on [Glass Mapper ImageParameters](http://www.glass.lu/Blog/ImageParameters) someone else mentions the same behavior. But there is no answer to it.

Original post on [Stackoverflow](https://stackoverflow.com/questions/34898648/sitecore-8-1-mvc-glass-mapper-v4-imagefield-renders-height-and-width-attribute-i)

**Comment by mikeedwards83** [comment]
Hi

I have added code to remove height and width in page edit mode, the only problem is that it also removed height and width from the URL in page edit mode. This is because Sitecore treats the width and height for both the URL and Image element as the same thing.

I think this is the best we can do without a change to the renderField pipeline and replacing the ImageRender.

Mike

**Comment by mikeedwards83** [comment]
Release in 4.0.9
