### ISSUE TITLE
Interface-based models are not serializable

### ISSUE THREAD

**Issue by jon-glass** [mikeedwards83/Glass.Mapper#303]
From what I can tell, when casting a sitecore model to a type that's an interface, Glass.Mapper creates a proxy for the interface. (versus a concrete class) When trying to serialize the mapped proxy object for session state, we get an error surrounding LazyObjectInterceptor not being serializable. 

e.g. service.GetItem<ISearch>(item, isLazy: false, inferType: true) returns a Castle.Proxies.ISearchProxy object that has an __interceptors field containing an array of the LazyObjectInterceptor objects that are not serializable. 

Is there a way to make interfaces/proxies serializable so they can be store in session state, just like concrete classes? 

```
[SerializationException: Type 'Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.LazyObjectInterceptor' in Assembly 'Glass.Mapper, Version=4.3.4.196, Culture=neutral, PublicKeyToken=null' is not marked as serializable.]
   System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type) +14156472
   System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context) +319
   System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo() +188
   System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder) +250
   System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder) +96
   System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck) +710
   System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck) +208
   System.Web.Util.AltSerialization.WriteValueToStream(Object value, BinaryWriter writer) +2262
```

**Comment by mikeedwards83** [comment]
Hi

This feature should already work. We have unit test that shows this working:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Tests/Unit%20Tests/Glass.Mapper.Sc.FakeDb/SerializationFixture.cs#L48

Mike

**Comment by cardinal252** [comment]
Yes, you would simply need to mark your glass mapped class / interface with the [Serializable] attribute to allow it to work. If you look to the parent library Castle DynamicProxy, there is a lot more information about serialization of proxies.

Nat

**Comment by RyanTuckNZ** [comment]
Hey guys, I'm encountering this issue as well, do I just need to upgrade to a later version?

LazyObjectInterceptor doesn't seem to be decorated with Serializable and I cant serialize an object to Mongo Shared SessionState that contains a Glass inherited type i.e. a custom class that has a Glass generated object as a property. Works fine InProc, but switching to Mongo Shared SessionState blows up on serializing LazyObjectInterceptor.

I've modified the T4 templates to make every generated type have the Serializable attribute,  and tried using concrete classes instead of interfaces in my custom 'Type' data, but still failing on Serializing LazyObjectInterceptor.:

Exception: System.Runtime.Serialization.SerializationException
Message: Type 'Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.LazyObjectInterceptor' in Assembly 'Glass.Mapper, Version=4.2.1.190, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
Source: mscorlib
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, Se
rializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, Serial
izationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Web.Util.AltSerialization.WriteValueToStream(Object value, BinaryWriter writer)

**Comment by mikeedwards83** [comment]
Unfortunately this isn't as simple as just adding the attribute to this single class. We also have to ensure that lazy objects are correctly expanded before being serialised which becomes more complex.

Due to the nature and security risks that are associated with just automatically serialising large object graphs this isn't something we will implemented.

It is safer and cleaner that you explicitly create the object graphs that you want to serialise.
