### ISSUE TITLE
Fallback field mapping

### ISSUE THREAD

**Issue by vasiliyfomichev** [mikeedwards83/Glass.Mapper#309]
Hey Mike,

Feature request - I'find myself running into this over and over again, where we are building custom logic for a fallback field for property mapping. For instance, for page title meta tag we would map it to its own Page Title field field, however, if that is empty - we would fall back to a field that's always populated to prevent empty page titles, or even a DisplayName, for instance. It would be really cool to have an elegant way to do this using Glass Mapper syntax, so we could specify a fallback field along with the primary one.

Cheers!

**Comment by mikeedwards83** [comment]
Hi

I normally achieve this with the following setup:

    public class MyModel
    {
        [SitecoreField(Setting = SitecoreFieldSettings.PageEditorOnly, FieldName = "PageTitle")]
        public virtual string Title
        {
            get { return string.IsNullOrWhiteSpace(PageTitle) ? DisplayName : PageTitle; }
        }

        [SitecoreField]
        protected virtual string PageTitle { get; set; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        protected virtual string DisplayName { get; set; }

    }


You can then use this on the page like so:

      @Html.Glass().Editable(model, x=> x.Title);

The reason I wouldn't want to include fallback in the framework is that it is rendering/business logic rather than mapping logic. Different projects may want fallback in different ways and we wouldn't be able to make everyone happy.
