### ISSUE TITLE
Class property of Sitecore MailTo LinkType is not mapping properly

### ISSUE THREAD

**Issue by nebulae1** [mikeedwards83/Glass.Mapper#324]
The general link field type has a mailto LinkType and this seems to have a "style" property on the ui but I cannot find this property within the Link class. I only see a "class" property. When this type of link is used, after mapping the class property is null when it should be populated.

**Comment by mikeedwards83** [comment]
Hi

Thanks for informing me of this. I have not accepted your pull request because the style attribute should be mapped to a style property. Additional GlassHtml needed to be update to render the style attribute. 

You can see the change I have made in the following commit:

https://github.com/mikeedwards83/Glass.Mapper/commit/7909d22aca101ded20bb225789b78a2a87d39258

**Comment by mikeedwards83** [comment]
Closed in release 4.5.0.202
