### ISSUE TITLE
BeginRenderLink not outputting an anchor when link is null

### ISSUE THREAD

**Issue by SNiels** [mikeedwards83/Glass.Mapper#329]
When Link is null, no anchor is printed out. I would expect an anchor without href to be printed out.
This is an issue in my project because CSS expects there to be an anchor.
```
@using (BeginRenderLink(Model, m => m.Link, new { @class = "btn btn-icon btn-default" }))
{
    ...
}
```

When I make the link editable, it is always printed out, but that creates another editframe (which doesn't to make the link editable anyway in my project).
Currently this is my workaround, but I would prefer to have an optional argument, or that the default behavior changes to always output an anchor.

Workaround:
```
@using (BeginRenderLink(Model, m => m.Link, new { @class = "btn btn-icon btn-default" }))
{
    if (Model.Link == null)
    {
        @Html.Raw("<a class=\"btn btn-icon btn-default\">")
    }

    ...

    if (Model.Link == null)
    {
        @Html.Raw("</a>")
    }
}
```

**Comment by mikeedwards83** [comment]
Hi

I can't change this behaviour directly because it will cause backward compatibility issues but I have added an alwaysRender parameter to BeginRenderLink, see this commit:

https://github.com/mikeedwards83/Glass.Mapper/commit/8e93dd127b8a06b731f3bedcf7f5c68b485676f6

What do you think to this solution?

Mike

**Comment by SNiels** [comment]
Hi, I expected that would be the case regarding backwards compatibility.
That looks exactly like what  I need, thank you!
