### ISSUE TITLE
CacheKeyGenerator and InferType – Undesired result.

### ISSUE THREAD

**Issue by PolarbearDK** [mikeedwards83/Glass.Mapper#341]
In our application we have implemented inheritance between glass models.

For example
Page is a TopPage is a IconMenuItem is a MenuItemBase is a GlassBase.

All models are loaded with inferType=True, but the requested type is different in different parts of the application.  

The problem is that because cache key is constructed using context.RequestedType.FullName then we end up with multiple identical Glass versions in cache of the same Sitecore Item (only varying by RequestedType).

When using inferType=True, then the object will always be the inferred type, and the ”RequestedType” should not be a vector in the cache key.

I suggest the following change to CacheKeyGenerator:
```CSHARP
return string.Format("{0}{1}{2}{3}{4}{5}{6}{7}",
    context.SitecoreService.GlassContext.Name,
    Sitecore.Context.Site == null ? string.Empty : Sitecore.Context.Site.Name,
    context.Item.ID,
    context.Item["__Revision"],
    context.Item.Language.Name,
    context.Item.Database.Name,
    context.InferType ? "Infer" : context.RequestedType.FullName,
    context.IsLazy
    );
```

”Infer” could be replaced with the FullName of the inferred type if that is possible.

I also suggest that dependencyResolver be expanded with a GetCacheKeyGenerator() method enabling ICacheKeyGenerator to be injected.

I can create pull requests for it if that is desired.

**Comment by mikeedwards83** [comment]
Hi

Thanks for raising this issue but i think the current solution is the desired behaviour. If we move to using "Infer" as part of the key it is possible that different inference type trees would result in the wrong type being returned.

For example, imagine the scenario where we have these two trees:

    public class Tree1 {} 
    public class Tree1Sub : Tree1{}   

    public class Tree2 {} 
    public class Tree2Sub : Tree2{}

If we used "Infer" as part of the key then we would have a problem if two different components need to infer type and cache the model but using the different trees. 

Component 1 would request Tree1 and get Tree1Sub which would be cached. When component 2 requests Tree2 the generated cache key would be the same as for Tree1Sub, so Tree1Sub would be returned. This would cause a casting exception because Tree1Sub cannot be case to Tree2.

Another option might be to cache based on the final type and not the requested type:

            return string.Format("{0}{1}{2}{3}{4}{5}{6}{7}",
                context.SitecoreService.GlassContext.Name,
                Sitecore.Context.Site == null ? string.Empty : Sitecore.Context.Site.Name,
                context.Item.ID,
                context.Item["__Revision"],
                context.Item.Language.Name,
                context.Item.Database.Name,
                args.Configuration.Type.FullName,
                context.Options.Lazy
                );

I will have a think.

**Comment by PolarbearDK** [comment]
Hi

I had forgot all about this post. 

Yes, The ”Infer” string should always be replaced with the FullName of the inferred type, otherwise it would lead to all sort of problems.

Another optimization you might want to consider is this:
If you load an model/item without lazy, and then later load the same model/item with lazy, you end up with two objects in cache for the same item. It would be better to check for a non lazy version and return that if possible (it would require two cache lookups though).

If this is nonsense then it's probably because its been a while since I visited this particular rabbit hole.

**Comment by mikeedwards83** [comment]
Closing, I think this has been implemented in the cachekeygenerator.

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/Caching/CacheKeyGenerator.cs
