### ISSUE TITLE
Bring back documentation, or host it on the github wiki

### ISSUE THREAD

**Issue by AdamHess** [mikeedwards83/Glass.Mapper#352]
Since offering paid training, nearly all documentation was wiped from glass.lu and is only available via the wayback machine.

To have a healthy, robust and GROWING community of developers, comprehensive free product documentation is needed.

I get wanting to have developers pay for training, but the paid training documentation is: 

1. just text, no interactive. 
2. less comprehensive than old documentation.

**Comment by mikeedwards83** [comment]
Hi Adam

Thanks for your feedback. 

The course is a combination or text/workshops and quizzes. I specifically didn't include videos in the course because personally I find it easier to scan and read text information when I am learning.

I disagree with the assertion that the training is less comprehensive than the original documentation. The course covers in more detail all the major Glass features. 

What would you want see in terms of interactivity in the training? What would make you happy to do the training course? What could be improved on the current training course?

The paid for course is also intended to make Glass.Mapper sustainable for the long run; to cover the cost of hosting the site and pay for some of the time I have spent/spend developing and supporting the framework. 

Mike

**Comment by issaco** [comment]
At least return the documentation for pre-5.0. going to have real issues down the track if anyone needs to work on an old project and what we trusted you to keep hosting was removed without warning.
