### ISSUE TITLE
GetRenderingParameters exception with MapMvcAttributeRoutes

### ISSUE THREAD

**Issue by corywdixon** [mikeedwards83/Glass.Mapper#91]
When testing attribute routing with Sitecore 7.2 using Glass.Sc.Mvc 3.2.0.41exception is thrown on reflection of GlassController.

Cannot call action method 'T GetRenderingParameters[T]()' on controller 'Glass.Mapper.Sc.Web.Mvc.GlassController' because the action method is a generic method.

**Comment by mikeedwards83** [comment]
Released

**Comment by crispynewt** [comment]
Hi,

I'm experiencing a similar problem with both 3.3.1.48 and 4.0.0.4

Cannot call action method 'T GetContextItem[T](Boolean, Boolean)' on controller 'Glass.Mapper.Sc.Web.Mvc.GlassController' because the action method is a generic method.

It seems that:
GetContextItem<T>
GetDataSourceItem<T>
GetLayoutItem<T>
are public which means that the above issue with attribute routing has returned.

Can these also be made protected?
Thanks :)

**Comment by lsj-oxygen** [comment]
The problem is indeed back. As crispynewt mentions, those methods need to be made protected as well or the call to "MapMvcAttributeRoutes()" will fail with the aforementioned error message.

I am having this issue while trying to use attribute routing with MVC 5 (5.2.3) and Sitecore 8.

**Comment by mikeedwards83** [comment]
The issue has been moved to here:
https://github.com/mikeedwards83/Glass.Mapper/issues/153

Please either open new issues or reopen a closed issue otherwise it might get missed.
