### ISSUE TITLE
Rendering Links does not keep multiple query string parameters that have the same name

### ISSUE THREAD

**Issue by PatrickDelancy** [mikeedwards83/Glass.Mapper#99]
Sitecore General Link field, set to an external link with query string parameters, like this: http://www.somedomain.com/that-one-page?param1=A&param1=B&param1=C

When using Glass MVC methods to render the link in a razor view (with Editable(), for example), the output URL looks like this:
http://www.somedomain.com/that-one-page?param1=C

If I can find some time, I'll look at the source and see if I can track it down, but I just wanted to put this out there while right away.

**Comment by mikeedwards83** [comment]
To build the URL Glass uses Sitecore.Text.UrlBuilder. There is a problem with the class and how it processes parameters.

**Comment by mikeedwards83** [comment]
More specifically it looks like it is a problem with the call to Sitecore.Web.WebUtil.ParseQuery. Internally this method uses a dictionary to track the query string parameters. This is causing duplicate keys to be overwritten.

**Comment by PatrickDelancy** [comment]
Thanks for the reply, Mike!

When I take Glass out of it, and use `@Html.Sitecore().Field()`, then it renders all of the parameters correctly. We're using Sitecore 7.2 rev. 140526.

I traced it down through the RenderField pipeline, and it uses `Sitecore.Xml.Xsl.LinkRenderer` which uses some other helpers, but I couldn't find anywhere that it called `UrlBuilder` or `WebUtil.ParseQuery` for external urls

I have to keep this client project moving, so for now we're just going to use @Html.Sitecore().Field() in a couple places, but I have it on my list to come back and take a closer look, maybe even submit a pull request if that's okay with you, but it doesn't look like that will happen for at least another week or two.

**Comment by mikeedwards83** [comment]
A fix for this has been pushed into the develop branch and will be available from the nightly build server tomorrow in the pre-release.

Let me know if you have any problems getting the release.

**Comment by rootix** [comment]
Hi Mike

Your change fixed another problem which i experience at the moment. If i have the following input: http://site/-/media/file.pdf?la=en&vs=1 the output of the url after going trough GlassHtml.BeginRenderLink is: http://site/-/media/file.pdf?vs=1&la=en. This is basically not a problem, but our Google Search Appliance crawls the documents in both versions because of different implementations (Media links in Rich Text stays the first way) and threat them as two documents. 

Anyway. Your custom AddToQuerystring method leaves the order of the parameters intact. Is it possible to release this fix in the near future?

**Comment by mikeedwards83** [comment]
Hi

I am just putting in a few more fixes and then we should be ready to release very soon.

Miek

**Comment by mikeedwards83** [comment]
Released
